# Generated by Django 5.1.1 on 2024-10-03 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_is_student_customuser_is_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='second_name',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='third_name',
        ),
        migrations.AddField(
            model_name='customuser',
            name='username',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
    ]
